name: Java Application
on: [push]
jobs:
 Build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2 
    - name: Check Java Version
      run: java --version
    - name: Validate Gradle
      run: gradle --version 
    - name: Build with Gradle
      run: gradle build
    - run: ls ./build/libs
    - name: Upload the file
      uses: actions/upload-artifact@v2
      with:
        path: ./build/libs/
        retention-days: 5
 Test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Execute the artefact
      run: java .jar ./build/libs/cars-api.jar
    
