name: Java Application
on: [push]
jobs:
 Build:
   runs-on: ubuntu-latest
   steps:
    - name: Check Java Version
      run: java --version
    - name: Build using Gradle
      run: /gradlew --version
  
    
