name: Java Application
on: [push]
jobs:
 Build:
   runs-on: ubuntu-latest
   steps:
      uses: actions/checkout@v2
    - name: Check Java Version
      run: java --version
    - name: Build using Gradle
      run: /gradlew --version
  
    
