name: Java Application
on: [push]
jobs:
 Build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2 
    - name: Check Java Version
      run: java --version
    - name: Validate Gradle
      run: gradle --version 
    - name: Build with Gradle
      run: ./gradlew build
  
    
