name: Java Application
on: [push]
jobs:
 Build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2 
    - name: Check Java Version
      run: java --version
    - name: Validate Gradle
      run: gradle --version 
    - name: Build with Gradle
      run: gradle build
    - run: ls ./build/libs
    - name: Upload the file
      uses: actions/upload-artifact@v2
      with:
        name: CarApiJar
        path: ./build/libs/
        retention-days: 5
 Test:
  runs-on: ubuntu-latest
  needs: Build
  steps:
    - name: Download the artefact
      uses: actions/download-artifact@v2
      with:
       name: CarApiJar
    - name: Test run
      run: |
       java -jar cars-api.jar &
       sleep 30
       curl http://localhost/5000/cars/1 | grep -i "Ford"
    
